#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page
# The redirection must be a “301 Moved Permanently”

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
echo "Hello World!" | sudo tee /var/www/html/redirect_me.html
sudo sed -i "30i $ADD301_REDIRECT" /etc/nginx/sites-available/default
sudo service nginx start
