#!/usr/bin/env bash
# configures a server to run and listen on port 80 of all the server’s active IPv4 IPs
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

sudo sed -i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf

# Start Nginx
service nginx start
