#!/usr/bin/env bash
# configures an Ubuntu server with the following requirements:
#	configures an Ubuntu server
#	facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.tmp
echo "127.0.0.2 	localhost"> ~/hosts.tmp
echo "8.8.8.8		facebook.com">>~/hosts.tmp
cp -f ~/hosts.tmp /etc/hosts
